my first homework
Olena-hrechana/test-repo pull request #5
Opened 2024-04-15 17:57 UTC by Olena-hrechana

2024-04-15 19:23 UTC, myroslav-kolomiiets requested changes

2024-04-15 19:23 UTC, myroslav-kolomiiets commented on myfile.js
> +let x : Number = 10;
В JS не має типів, це звідки взято?)

Також всі змінні, що не перезаписуються в подальшому виконанні скрипта, треба об'являти через константи.
```suggestion
const x = 10;
```

2024-04-15 19:23 UTC, myroslav-kolomiiets commented on myfile.js
> +let x : Number = 10;
І так далі

2024-04-15 21:34 UTC, Olena-hrechana commented on myfile.js
> +let x : Number = 10;
> В JS не має типів, це звідки взято?)

з лекції)
 але потім зрозуміла, що тип автоматично відображався у webstorm.

2024-04-16 09:21 UTC, myroslav-kolomiiets commented on myfile.js
> +let x : Number = 10;
О, хороший пойнт, до речі, дякую. Буду про це говорити явно, бо може бути не очевидно.

2024-04-16 09:21 UTC, myroslav-kolomiiets approved these changes

2024-04-16 16:46 UTC, merged